# Gemini API 金鑰設定
# 警告：請勿將此檔案上傳到公開的 Git 儲存庫。
# 請在這裡貼上您新的、安全的 Google AI API 金鑰。
gemini_api_key: ""

# 模型設定
model_name: "gemini-1.5-flash-latest"

# 生成設定 (可選)
temperature: 0.7
top_p: 1.0
top_k: 32
max_output_tokens: 4096
